### ISSUE TITLE
[BUG] HTML code view into the "about" section

### ISSUE THREAD

**Issue by ghost** [devnied/EMV-Reader-translation#4]
### Bug report

In the "about" page, **HTML** isn't compiled, but the code was showed as a sinple string.

The `TextView` doesn't know HTML and it not execute it. To fix them, please try to follow this steps
1. Delte code and wrie only your app text
2. Use the `link` attribute to create an `hypertext`
3. Compile app and relase patch

**Comment by devnied** [comment]
I can't reproduce your issue.
Can you give me the model of your phone and your Android version please ?

**Comment by rowdy86** [comment]
Hi, what is this kind of bug?

Sendt fra Outlook Mobile

On Fri, May 20, 2016 at 3:18 PM -0700, "Julien Millau" notifications@github.com wrote:

I can't reproduce your issue.
Can you give me the model of your phone and your Android version please ?

---

**Comment by yanitsa85** [comment]
Samsung galaxy 6 edges

**Comment by Mez050** [comment]
Samsung Note 3 android version 5.0

**Comment by ericchong881** [comment]
Samsung galaxy J5
